import { IconType } from 'react-icons';
import {
    FaTwitter,
    FaHome,
    FaHashtag,
    FaBell,
    FaEnvelope,
    FaBookmark,
    FaListUl,
    FaUserAlt,
    FaEllipsisH,
    FaRegArrowAltCircleLeft,
    FaRegArrowAltCircleRight,
    FaRegArrowAltCircleUp,
    FaRegArrowAltCircleDown,
    FaRegHeart,
    FaRegComment,
    FaRetweet,
    FaShareSquare,
    FaSearch,
} from 'react-icons/fa';

export const TwitterIcon: Record<string, IconType> = {
    Twitter: FaTwitter,
    Home: FaHome,
    Hashtag: FaHashtag,
    Bell: FaBell,
    Envelope: FaEnvelope,
    Bookmark: FaBookmark,
    List: FaListUl,
    User: FaUserAlt,
    More: FaEllipsisH,
    LeftArrow: FaRegArrowAltCircleLeft,
    RightArrow: FaRegArrowAltCircleRight,
    UpArrow: FaRegArrowAltCircleUp,
    DownArrow: FaRegArrowAltCircleDown,
    Heart: FaRegHeart,
    Comment: FaRegComment,
    Retweet: FaRetweet,
    Share: FaShareSquare,
    Search: FaSearch,
};
